export const SELECT_HOURS = 'SELECT_HOURS';
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';
export const CHANGE_PERSONAL = 'CHANGE_PERSONAL';
export const CONFIRM_BOOKING = 'CONFIRM_BOOKING';
export const CONFIRM_PHONE_NUMBER = 'CONFIRM_PHONE_NUMBER';
export const SELECT_SERVICES = 'SELECT_SERVICES';